Global Unemployment Analysis (1991–2024)

In [20]:
import numpy as nb
import pandas as pd

In [ ]:
# Highest unemployment country and year.
# Lowesart unemployment country and year.
# Top 10 countries by average unemployment.
# Bottom 10 countries by average unemployment.
# Global average unemployment by year.
# Year with highest global unemployment.
# Year with lowest global unemployment.
# Most stable country.
# Most volatile country.
# Countries with the largest improvement from 1991 to 2024.

In [63]:
df_unemployment.head()

,Country,Country _code,Indicator_name,Indicator_code,year,Value
0,Africa Eastern and Southern,AFE,Unemployment,SL.UEM.TOTL.ZS,1991,8.050809
1,Africa Eastern and Southern,AFE,Unemployment,SL.UEM.TOTL.ZS,1992,8.158273
2,Africa Eastern and Southern,AFE,Unemployment,SL.UEM.TOTL.ZS,1993,8.155910
3,Africa Eastern and Southern,AFE,Unemployment,SL.UEM.TOTL.ZS,1994,8.022100
4,Africa Eastern and Southern,AFE,Unemployment,SL.UEM.TOTL.ZS,1995,7.773894

In [69]:
df_unemployment.drop('Indicator_code',axis=1)

                          Country Country _code Indicator_name  year     Value
0     Africa Eastern and Southern           AFE   Unemployment  1991  8.050809
1     Africa Eastern and Southern           AFE   Unemployment  1992  8.158273
2     Africa Eastern and Southern           AFE   Unemployment  1993  8.155910
3     Africa Eastern and Southern           AFE   Unemployment  1994  8.022100
4     Africa Eastern and Southern           AFE   Unemployment  1995  7.773894
...                           ...           ...            ...   ...       ...
8171                       Zambia           ZMB   Unemployment  2021  5.197000
8172                       Zambia           ZMB   Unemployment  2022  5.993000
8173                       Zambia           ZMB   Unemployment  2023  5.861000
8174                       Zambia           ZMB   Unemployment  2024  5.898000
8175                       Zambia           ZMB   Unemployment  2025  5.918000

[8176 rows x 5 columns]

In [71]:
df_unemployment.isna().sum()

Country           0
Country _code     0
Indicator_name    0
Indicator_code    0
year              0
Value             0
dtype: int64

In [72]:
df_unemployment.isna().any()

Country           False
Country _code     False
Indicator_name    False
Indicator_code    False
year              False
Value             False
dtype: bool

In [76]:
df_unemployment['Value']

0       8.050809
1       8.158273
2       8.155910
3       8.022100
4       7.773894
          ...
8171    5.197000
8172    5.993000
8173    5.861000
8174    5.898000
8175    5.918000
Name: Value, Length: 8176, dtype: float64

In [78]:
def highest_unemployment_country(df):
    filtered = df_unemployment[(df_unemployment['year'] >= 1991) & (df_unemployment['year'] <= 2024)]

    highest = filtered.loc[filtered['Value'].idxmax()]

    return {
        "Country": highest["Country"],
        "Year": highest["year"],
        "Value": highest["Value"]
    }

result = highest_unemployment_country(df_unemployment)
print(result)

{'Country': 'North Macedonia', 'Year': np.int64(1996), 'Value': np.float64(38.8)}

In [88]:
df_unemployment.info

<bound method DataFrame.info of                           Country Country _code Indicator_name  \
0     Africa Eastern and Southern           AFE   Unemployment
1     Africa Eastern and Southern           AFE   Unemployment
2     Africa Eastern and Southern           AFE   Unemployment
3     Africa Eastern and Southern           AFE   Unemployment
4     Africa Eastern and Southern           AFE   Unemployment
...                           ...           ...            ...
8171                       Zambia           ZMB   Unemployment
8172                       Zambia           ZMB   Unemployment
8173                       Zambia           ZMB   Unemployment
8174                       Zambia           ZMB   Unemployment
8175                       Zambia           ZMB   Unemployment

      Indicator_code  year     Value
0     SL.UEM.TOTL.ZS  1991  8.050809
1     SL.UEM.TOTL.ZS  1992  8.158273
2     SL.UEM.TOTL.ZS  1993  8.155910
3     SL.UEM.TOTL.ZS  1994  8.022100
4     SL.UEM.TOTL.ZS  1995  7.773894
...              ...   ...       ...
8171  SL.UEM.TOTL.ZS  2021  5.197000
8172  SL.UEM.TOTL.ZS  2022  5.993000
8173  SL.UEM.TOTL.ZS  2023  5.861000
8174  SL.UEM.TOTL.ZS  2024  5.898000
8175  SL.UEM.TOTL.ZS  2025  5.918000

[8176 rows x 6 columns]>

In [90]:
df_unemployment.drop('Indicator_code',axis=1,inplace= True)

In [91]:
df_unemployment

                          Country Country _code Indicator_name  year     Value
0     Africa Eastern and Southern           AFE   Unemployment  1991  8.050809
1     Africa Eastern and Southern           AFE   Unemployment  1992  8.158273
2     Africa Eastern and Southern           AFE   Unemployment  1993  8.155910
3     Africa Eastern and Southern           AFE   Unemployment  1994  8.022100
4     Africa Eastern and Southern           AFE   Unemployment  1995  7.773894
...                           ...           ...            ...   ...       ...
8171                       Zambia           ZMB   Unemployment  2021  5.197000
8172                       Zambia           ZMB   Unemployment  2022  5.993000
8173                       Zambia           ZMB   Unemployment  2023  5.861000
8174                       Zambia           ZMB   Unemployment  2024  5.898000
8175                       Zambia           ZMB   Unemployment  2025  5.918000

[8176 rows x 5 columns]

In [95]:
print(df_unemployment.columns.tolist())

['Country', 'Country _code', 'Indicator_name', 'year', 'Value']

In [97]:
df_unemployment.groupby('Country')['Value'].mean().sort_values(ascending=False)

Country
North Macedonia    27.978086
Djibouti           26.519429
Eswatini           26.412657
South Africa       25.242571
Montenegro         22.931771
                     ...
Bahrain             1.135857
Myanmar             1.135771
Chad                0.909571
Cambodia            0.643000
Qatar               0.528571
Name: Value, Length: 234, dtype: float64

In [96]:
 # Highest unemployment country and year.
highest = df_unemployment.loc[df_unemployment['Value'].idxmax()]

print("Country:", highest['Country'])
print("Year:", highest['year'])
print("Unemployment Rate:", highest['Value'])

Country: North Macedonia
Year: 1996
Unemployment Rate: 38.8

In [98]:
#  Lowest unemployment country and year.
lowest_row = df_unemployment.loc[df_unemployment['Value'].idxmin()]

print("Country:", lowest_row['Country'])
print("Year:", lowest_row['year'])
print("Lowest Unemployment Rate:", lowest_row['Value'])

Country: Qatar
Year: 2019
Lowest Unemployment Rate: 0.1

In [99]:
# Top 10 countries by average unemployment
top10_avg_unemployment = (
    df_unemployment
    .groupby('Country')['Value']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(top10_avg_unemployment)

Country
North Macedonia                   27.978086
Djibouti                          26.519429
Eswatini                          26.412657
South Africa                      25.242571
Montenegro                        22.931771
Bosnia and Herzegovina            22.431371
Namibia                           20.801743
Congo, Rep.                       20.079714
Botswana                          19.688343
St. Vincent and the Grenadines    19.622886
Name: Value, dtype: float64

In [100]:
# Bottom 10 countries by average unemployment.
bottom10_avg_unemployment = (
    df_unemployment
    .groupby('Country')['Value']
    .mean()
    .sort_values(ascending=True)
    .head(10)
)

print(bottom10_avg_unemployment)

Country
Qatar              0.528571
Cambodia           0.643000
Chad               0.909571
Myanmar            1.135771
Bahrain            1.135857
Thailand           1.266971
Niger              1.267000
Benin              1.381200
Solomon Islands    1.598229
Kuwait             1.644943
Name: Value, dtype: float64

In [101]:
# Global average unemployment by year.
global_avg_yearly = (
    df_unemployment
    .groupby('year')['Value']
    .mean()
)

print(global_avg_yearly)

year
1991    7.310221
1992    7.660805
1993    8.082502
1994    8.231577
1995    8.271240
1996    8.380834
1997    8.250378
1998    8.303485
1999    8.456863
2000    8.335405
2001    8.334309
2002    8.483475
2003    8.472402
2004    8.266889
2005    8.039270
2006    7.625847
2007    7.252159
2008    7.167689
2009    7.932414
2010    8.047744
2011    7.989597
2012    8.046049
2013    8.041793
2014    7.861012
2015    7.792736
2016    7.656497
2017    7.440393
2018    7.202555
2019    7.051167
2020    8.103436
2021    7.796494
2022    6.907438
2023    6.495708
2024    6.435235
2025    6.439277
Name: Value, dtype: float64

In [102]:
# Year with highest global unemployment
global_avg_yearly = (
    df_unemployment
    .groupby('year')['Value']
    .mean()
)

highest_year = global_avg_yearly.idxmax()

print("Year with Highest Global Unemployment:", highest_year)
print("Average Unemployment:", global_avg_yearly.max())

Year with Highest Global Unemployment: 2002
Average Unemployment: 8.48347472847436

In [103]:
# Year with highest global unemployment
global_avg_yearly = (
    df_unemployment
    .groupby('year')['Value']
    .mean()
)

lowest_year = global_avg_yearly.idxmin()

print("Year with Lowest Global Unemployment:", lowest_year)
print("Average Unemployment:", global_avg_yearly.min())

Year with Lowest Global Unemployment: 2024
Average Unemployment: 6.435234609026201

In [104]:
# most stable country
stable_country = (
    df_unemployment
    .groupby('Country')['Value']
    .std()
    .sort_values()
    .head(1)
)

print("Most Stable Country (Lowest Variation):")
print(stable_country)

Most Stable Country (Lowest Variation):
Country
Bahrain    0.155293
Name: Value, dtype: float64

In [105]:
# most 
volatile_country = (
    df_unemployment
    .groupby('Country')['Value']
    .std()
    .sort_values(ascending=False)
    .head(1)
)

print("Most Volatile Country (Highest Variation):")
print(volatile_country)

Most Volatile Country (Highest Variation):
Country
North Macedonia    8.061324
Name: Value, dtype: float64

In [107]:
# get average (safe in case multiple entries per country-year)
df_1991 = df_unemployment[df_unemployment['year'] == 1991].groupby('Country')['Value'].mean()
df_2024 = df_unemployment[df_unemployment['year'] == 2024].groupby('Country')['Value'].mean()

# combine into one DataFrame
improvement = pd.DataFrame({
    '1991': df_1991,
    '2024': df_2024
})

# drop missing values (countries not present in both years)
improvement = improvement.dropna()

# calculate improvement
improvement['Change'] = improvement['1991'] - improvement['2024']

# sort to find biggest improvement
top_improved = improvement.sort_values('Change', ascending=False)

print(top_improved.head(10))

                       1991    2024  Change
Country
Montenegro           30.118  13.206  16.912
Barbados             22.410   6.448  15.962
Trinidad and Tobago  18.520   3.318  15.202
Zambia               18.900   5.898  13.002
North Macedonia      24.500  12.265  12.235
Ireland              15.771   4.300  11.471
Poland               13.621   2.807  10.814
Puerto Rico (US)     16.180   5.639  10.541
Sri Lanka            14.661   4.239  10.422
Israel               13.387   3.595   9.792